[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
version="1.14.2"
name = "icloudpd"
description = "icloudpd is a command-line tool to download photos and videos from iCloud."
readme = "README_PYPI.md"
requires-python = ">=3.7,<3.12"
keywords = ["icloud", "photo"]
license = {file="LICENSE.md"}
authors=[
    {name = "The iCloud Photo Downloader Authors"}
]
classifiers = [
        "Intended Audience :: Developers",
        "Operating System :: OS Independent",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
]
dependencies = [
    "requests>=2.28.2,<3",
    "schema>=0.7.5,<0.8",
    "click>=8.1.3,<9",
    "python-dateutil>=2.8.2,<3",
    "tqdm>=4.64.1,<5",
    "piexif>=1.1.3,<2",
    "urllib3>=1.26.14,<2",
    # from pyicloud_ipd
    "six>=1.16.0,<2",
    "tzlocal>=4.2,<5",
    "pytz>=2022.7.1,<2023",
    "certifi>=2022.12.7,<2023",
    "future>=0.18.3,<0.19",
    "keyring>=23.13.1,<24",
    "keyrings-alt>=4.2.0,<5"
]

[project.urls]
Homepage="https://github.com/icloud-photos-downloader/icloud_photos_downloader"

[project.scripts]
icloudpd = "icloudpd.base:main"
icloud = "pyicloud_ipd.cmdline:main"
