on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  get_version:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Retrieve version
      id: get_version
      run: |
        echo icloudpd_version=$(cat pyproject.toml | grep version= | cut -d'"' -f 2) >> $GITHUB_OUTPUT
        echo 'icloudpd_changelog<<EOF' >> $GITHUB_OUTPUT
        scripts/extract_releasenotes CHANGELOG.md >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT

    - name: Retrieve Changelog
      id: get_change_log
      run: |
        scripts/extract_releasenotes CHANGELOG.md > dist/changelog-${{steps.get_version.outputs.icloudpd_version}}.md

    - name: Log version and Changelog
      run: |
        echo "icloudpd_version=${{steps.get_version.outputs.icloudpd_version}}"
        cat dist/changelog-${{steps.get_version.outputs.icloudpd_version}}.md
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: icloudpd-${{ github.sha }}-changelog
        if-no-files-found: error
        path: |
          dist/changelog-*.md

    outputs:
      icloudpd_version: ${{steps.get_version.outputs.icloudpd_version}}

  build_package:
    needs: [get_version]
    uses: ./.github/workflows/build-package.yml
    with:
      icloudpd_version: ${{needs.get_version.outputs.icloudpd_version}}

  build_notes:
    needs: [get_version, build_package]
    runs-on: ubuntu-22.04
    steps:

    - name: Download artifacts (compatibility)
      uses: actions/download-artifact@v4
      with:
        name: icloudpd-${{github.sha}}-compatibility
        path: |
          dist

    - name: Download artifacts (changelog)
      uses: actions/download-artifact@v4
      with:
        name: icloudpd-${{github.sha}}-changelog
        path: |
          dist

    - name: Merge Release Notes
      run: |
        cat dist/changelog-*.md > dist/notes.md
        cat dist/compatibility-*.md >> dist/notes.md

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: icloudpd-${{ github.sha }}-notes
        if-no-files-found: error
        path: |
          dist/notes.md

  publish:
    needs: [get_version, build_package, build_notes]
    uses: ./.github/workflows/publish.yml
    with:
      icloudpd_version: ${{needs.get_version.outputs.icloudpd_version}}
      icloudpd_changelog: ${{needs.get_version.outputs.icloudpd_changelog}}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
