# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Quality Checks

on:
  push:
    # branches: [ master ]
  pull_request:
    # branches: [ master ]
  workflow_dispatch:

jobs:
  check_quality:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        include:
          - os: "ubuntu-latest"
          # There is no build for Python 3.6 in ubuntu>20.04.
          # This unclude can be removed when we drop support for Python 3.6.
          - os: "ubuntu-20.04"
            python-version: "3.6"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        scripts/install_deps

    - name: Lint
      run: |
        scripts/lint
        
    - name: Test
      run: |
        scripts/test

  validate_build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
        include:
          - os: "ubuntu-latest"
          # There is no build for Python 3.6 in ubuntu>20.04.
          # This unclude can be removed when we drop support for Python 3.6.
          - os: "ubuntu-20.04"
            python-version: "3.6"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        scripts/install_deps

    - name: Build
      run: |
        scripts/build

    - name: Build Release Docker
      run: |
        scripts/build_docker
      with:
        python-version: 3.9

    - name: Build Release Executable
      run: |
        pyinstaller --onefile icloudpd.py --name icloudpd-${{ matrix.os }}-${{ matrix.architecture }}
      with:
        python-version: 3.9

  validate_dev_docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Dev Docker
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: false
