# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test GH Release

on:
  push:
    branches:
      - '**'
  pull_request:
    # branches: [ master ]
  workflow_dispatch:

jobs:
  get_version:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Retrieve version and Changelog
      id: get_version
      run: |
        echo icloudpd_version=$(cat pyproject.toml | grep version= | cut -d'"' -f 2) >> $GITHUB_OUTPUT
        echo 'icloudpd_changelog<<EOF' >> $GITHUB_OUTPUT
        scripts/extract_releasenotes CHANGELOG.md >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT

    - name: Log version and Changelog
      run: |
        echo "icloudpd_version=${{steps.get_version.outputs.icloudpd_version}}"
        echo "icloudpd_changelog=${{steps.get_version.outputs.icloudpd_changelog}}"

    outputs:
      icloudpd_version: ${{steps.get_version.outputs.icloudpd_version}}
      icloudpd_changelog: ${{steps.get_version.outputs.icloudpd_changelog}}

  gh_release:
    needs: get_version
    runs-on: ubuntu-22.04
    steps:

      - uses: actions/checkout@v3

      - name: Merge body
        run: |
          echo "${{needs.get_version.outputs.icloudpd_changelog}}" > body.md
          echo '## Test' >> body.md
          cat CHANGELOG.md >> body.md

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "CHANGELOG.md,body.md"
          # body: ${{needs.get_version.outputs.icloudpd_changelog}}
          bodyFile: body.md
          tag: 'v1.17.4-dev4'
